### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jetrom17** [DiegoRamosGomes/tabnews-app#7]
Não sei se é na minha máquina ou no seu código. 

```/home/jetronix/``` (Meu).

Após executar:

```
 ~/tabnews-app/ [master*] npx expo start
(node:52228) UnhandledPromiseRejectionWarning: Error: Cannot find module 'fs/promises'
Require stack:
- /home/jetronix/tabnews-app/node_modules/@expo/cli/build/src/start/doctor/typescript/TypeScriptProjectPrerequisite.js
- /home/jetronix/tabnews-app/node_modules/@expo/cli/build/src/start/startAsync.js
- /home/jetronix/tabnews-app/node_modules/@expo/cli/build/src/start/index.js
- /home/jetronix/tabnews-app/node_modules/@expo/cli/build/bin/cli
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/jetronix/tabnews-app/node_modules/@expo/cli/build/src/start/doctor/typescript/TypeScriptProjectPrerequisite.js:5:40)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
(node:52228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:52228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DiegoRamosGomes** [comment]
Apague a pasta `node_modules` e rode o comando `yarn install` novamente, caso o problema persista por favor coloque aqui qual versão do node vc esta usando para que eu possa reproduzir o erro com mais detalhes

**Comment by Jetrom17** [comment]
![IMG_20221127_112848842_HDR.jpg](https://user-images.githubusercontent.com/72875404/204140552-c17ae603-db24-4f54-9698-4c786a7d6ef8.jpg)

Não sei como atualizar essa versão. Acretido que seja isso problema.

**Comment by DiegoRamosGomes** [comment]
vc precisa atualizar seu node, esta usando a versão 12 que á é mais antiga

também de um pull no projeto para atualizar os arquivos `git pull origin master`

para atualizar eu costumo apagar a versão antiga e baixar a nova do proprio site do node, mas existem varias formas de fazer isso
